.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 Kevin Paul Herbert <kph@platinasystems.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GOES-BOOT-EXAMPLE-AMD64 1 "March 19, 2020"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
goes-boot-example-amd64 \- Test environment for goes-boot using qemu
.SH SYNOPSIS
.B goes-boot-example-amd64
.SH DESCRIPTION
This manual page documents briefly the
.B goes-boot-example-amd64
program.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBgoes-boot-example-amd64\fP is a version of goes-boot intended for development
purposes using qemu-system-x86_64.
